services:
  web:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    command:
      - /app/env/bin/gunicorn
      - --reload
      - -b
      - "[::]:8000"
      - -w
      - "2"
      - scripts.boxesserver
    environment:
      STATIC_URL: /static
    volumes:
      - /app/env
      - /app/scripts
      - ./:/app
      - /mnt/c/Users/schoennagel/Pictures:/mnt/c/Users/schoennagel/Pictures:ro
      - /mnt/c/Users/schoennagel/ownCloud/Documents/Science/Trailer-Hardware:/mnt/c/Users/schoennagel/ownCloud/Documents/Science/Trailer-Hardware:ro
    ports:
      - 4455:8000
